name: Python CI

# This workflow will run unit tests on push or pull request events

on:
  push:
    branches: 
        - main
  pull_request:
    branches: 
         - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
       # Checkout the code from repository
       - name: Checkout code
         uses: actions/checkout@v2
       # Set up Python environment
       - name: Set up Python
         uses: actions/setup-python@v2
         with:
           python-version: '3.14'
       # Install dependencies
       - name: Install dependencies
         run: |
              python -m pip install --upgrade pip
              pip install -r requirements.txt
              
       # Run unit tests
       - name: Run  tests
         run: pytest

        
    
